name: grizzly_range
description: Lazy and efficient 'range' iterables to generate values based on start, stop and step/count.
version: 3.0.0
homepage: https://github.com/Grizzly-dart/range
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  quiver_hashcode: ^3.0.0+1
  collection: ^1.15.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
