name: grizzly_range
description: Lazy and efficient 'range' iterables to generate values based on start, stop and step/count.
version: 2.0.2
homepage: https://github.com/Grizzly-dart/range
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  meta: ^1.1.7
  quiver_hashcode: ^2.0.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
