name: grizzly_range
description: Lazy and efficient 'range' iterables to generate values based on start, stop and step/count.
version: 2.0.9
homepage: https://github.com/Grizzly-dart/range

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  meta: ^1.7.0
  quiver: ^3.0.1+1
  collection: ^1.15.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
